### ISSUE TITLE
If config yaml is missing fields, gives `open : no such file`

### ISSUE THREAD

**Issue by njwilson23** [njwilson23/orogenesis#1]
The following valid configuration will work, but will emit as error because `footer` is not defined

``` yaml
template: ../templates/main-template.html
title-raw: Karta
header: karta/header.html
body: karta/body.html
```

Possible fix: substitute empty HTML strings for empty `Page` keys.
